import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import { ethers } from 'ethers';
import Head from 'next/head';
import connectContract from '../utils/connect';

const Home: NextPage = () => {
	const createEvent = async () => {
		try {
			const contract = connectContract();
			if (!contract) return;
			const txn = await contract.createEvent(
				'Event Name',
				new Date().valueOf(), // epoch time
				100, // capacity
				ethers.utils.parseEther('1') // 1 eth in gwei??
			);
			console.log('minting...');
			await txn.wait();
			console.log('minted!');
			console.log(txn);
		} catch (err) {
			console.log(err);
		}
	};
	return (
		<div>
			<Head>
				<title>RainbowKit App</title>
				<meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
				<link href="/favicon.ico" rel="icon" />
			</Head>

			<main>
				<label htmlFor="name">Event Name:</label>
				<input type="text" id="name"></input>
				<br />
				<label htmlFor="date">Date and Time:</label>
				<input type="text" id="date"></input>
				<br />
				<label htmlFor="Capacity">Capacity:</label>
				<input type="text" id="capacity"></input>
				<br />
				<label htmlFor="deposit">Deposit:</label>
				<input type="text" id="deposit"></input>
				<br />
				<button onClick={createEvent}>Submit</button>

				<ConnectButton />
			</main>
		</div>
	);
};

export default Home;
